global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Dagster code server doesn't expose Prometheus by default — we'll add a
  # /metrics endpoint via prometheus_client in week 6.
  - job_name: sentinel
    static_configs:
      - targets: ["dagster-webserver:9464"]
    metrics_path: /metrics
    scrape_interval: 30s
